#!/bin/sh

if [ $# -ne 3 ]
  then
	echo "Create a new fileshare on an existing azure storage account."
    echo "Usage: $(basename "$fullfile") <resource group> <storage account> <fileshare name>"
	exit 1
fi

RESOURCE_GROUP="$1"
STORAGE_ACCOUNT="$2"
FILESHARE_NAME="$3"

CONN_STRING="$(az storage account show-connection-string -n $STORAGE_ACCOUNT -g $RESOURCE_GROUP --query 'connectionString' -o tsv)"

az storage share create --name $FILESHARE_NAME --connection-string "$CONN_STRING" > /dev/null

if [ $? -eq 0 ]; then
    echo "Successfully created file share $FILESHARE_NAME"
else
    echo "Failed creating file share $FILESHARE_NAME on storage account $STORAGE_ACCOUNT"
	exit 1
fi